[project]
name = "nat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.8",
    "nvidia-nat[langchain,phoenix]>=1.3.1",
    "pandas>=2.3.3",
]
